name: Smoke Test Kubernetes Access

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.30.0"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: "v3.14.4"

      - name: Install utils
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq dnsutils netcat-openbsd

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl config current-context || true

      - name: Check API reachability (TCP 6443)
        run: |
          API_IP="103.132.230.3"
          nc -vz -w 5 "${API_IP}" 6443

      - name: kubectl cluster-info & version
        run: |
          kubectl cluster-info
          kubectl version --request-timeout=10s

      - name: RBAC check and nodes
        run: |
          kubectl auth can-i '*' '*' --all-namespaces
          kubectl get nodes -o wide

      - name: Helm template Rancher (dry-run)
        run: |
          helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
          helm repo update
          test -n "${{ vars.LETSENCRYPT_EMAIL }}" || (echo "Missing repo variable LETSENCRYPT_EMAIL" && exit 1)
          test -n "${{ vars.RANCHER_HOSTNAME }}" || (echo "Missing repo variable RANCHER_HOSTNAME" && exit 1)
          test -n "${{ secrets.RANCHER_BOOTSTRAP_PASSWORD }}" || (echo "Missing secret RANCHER_BOOTSTRAP_PASSWORD" && exit 1)
          helm template rancher rancher-stable/rancher \
            --namespace cattle-system \
            -f clusters/madiunkab/rancher/values.yaml \
            --set hostname=${{ vars.RANCHER_HOSTNAME }} \
            --set letsEncrypt.email=${{ vars.LETSENCRYPT_EMAIL }} \
            --set bootstrapPassword=${{ secrets.RANCHER_BOOTSTRAP_PASSWORD }} \
            >/dev/null
          echo "Helm template OK"

      - name: (Optional) DNS resolve Rancher hostname
        if: ${{ vars.RANCHER_HOSTNAME != '' }}
        run: |
          dig +short A "${{ vars.RANCHER_HOSTNAME }}" || true
